#
# MIT License
# Copyright (c) 2025 Youcef Lemsafer
# See LICENSE file for more details.
# Creation date: february 2025.
#

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensure submodules (like Catch2) are checked out

      # Set up a C++ environment (e.g., install gcc, make, etc.)
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      # Build Catch2
      - name: Build Catch2
        run: |
          mkdir -p Catch2-build && cd Catch2-build
          cmake ../Catch2 -DCMAKE_INSTALL_PREFIX=../Catch2-install
          cmake --build . --target install

      # Build the project using your Makefile
      - name: Build project
        run: make

      # Run the tests
      - name: Run tests
        run: ./tests  # Replace with the name of your tests executable

